### ISSUE TITLE
Consider changing namespace

### ISSUE THREAD

**Issue by samrap** [samrap/acf-fluent#5]
The `Acf` namespace does not properly reflect the package. Consider renaming this to a more descriptive namespace, or simply using `Samrap\Acf`.

**Comment by JulienMelissas** [comment]
I think `Samrap\ACF` would be cool. It makes sense for it to be your github handle (unless you wanted to make it the name of an organization or something like that). I also personally much prefer a capitalized "ACF" as it's an acronym.

**Comment by samrap** [comment]
I agree with the base namespace being `Samrap` as that is the convention. As far as the class name, there is a good discussion [here](https://groups.google.com/forum/#!topic/php-fig/rGopcf4WyyU) about following the PSR StudlyCaps rule when dealing with acronyms. I personally prefer following strictly to StudlyCaps as do some large frameworks like Zend, Laravel, etc. For that reason, I will be changing the full namespace to `Samrap\Acf`, leaving the class name unchanged  :)

**Comment by samrap** [comment]
Implementing this I realize it makes the most sense to namespace _everything_ under `Samrap\Acf`, so the final class name would be `Samrap\Acf\Acf`. Not sure how I feel about that. But without it, the internal classes are `Samrap\Fluent\Builder`, etc.

**Comment by samrap** [comment]
Confirming that the root namespace of this project will be `Samrap\Acf`.
